'use strict';
// Independent, reference-guided, per-read experimental signal decomposition.
// This module never transmits chromatograms or candidate variants.
(()=>{
const el=id=>document.getElementById(id), DNA='ACGT', candidates=[];
const comp={A:'T',C:'G',G:'C',T:'A'};
function refBase(pos,strand){const b=state.ref.seq[pos];return b?(strand===1?b:comp[b]||'N'):'N'}
function observed(read,k){if(k<0||k>=read.positions.length)return null;const p=read.positions[k],v=DNA.split('').map(b=>Math.max(0,read.traces[b][p]||0));const sum=v.reduce((a,b)=>a+b,0);return sum>40?v.map(x=>x/sum):null}
function loss(v,a,b,f){if(!v||!DNA.includes(a)||!DNA.includes(b))return null;let err=0;for(let i=0;i<4;i++){const pred=.015+.94*((a===DNA[i]?1-f:0)+(b===DNA[i]?f:0));err+=(v[i]-pred)**2}return err}
function baseline(read,k,ref0,dir){let e=0,n=0;for(let d=-13;d<=-3;d++){const x=loss(observed(read,k+d),refBase(ref0+dir*d,dir),refBase(ref0+dir*d,dir),0);if(x!==null){e+=x;n++}}return n>=8?e/n:null}
function estimateAnchor(read,k){const al=read.alignment,dir=al.strand==='+'?1:-1,points=[];for(const c of al.cols){if(c.q===null||c.r===null)continue;const q=dir===1?c.q:read.bases.length-1-c.q;if(q>=k-42&&q<=k-8)points.push(c.r-dir*q)}if(points.length<9)return null;points.sort((a,b)=>a-b);const offset=points[Math.floor(points.length/2)];let ok=0;for(let d=-22;d<=-4;d++){const pos=offset+dir*(k+d);if(read.bases[k+d]===refBase(pos,dir))ok++}return ok>=10?{ref0:offset+dir*k,dir,ok}:null}
function scan(read,k,anchor){const {ref0,dir}=anchor,pre=baseline(read,k,ref0,dir);if(pre===null||pre>.23)return null;const vals=[];for(let d=3;d<=28;d++){const v=observed(read,k+d),wt=refBase(ref0+dir*d,dir);if(v&&DNA.includes(wt))vals.push({d,v,wt})}if(vals.length<18)return null;const nullLoss=vals.reduce((s,x)=>s+loss(x.v,x.wt,x.wt,0),0)/vals.length;
let best=null;
// delta is a displacement along acquisition, not a genomic coordinate.
for(let delta=-20;delta<=20;delta++){if(!delta)continue;for(let f=.25;f<=.751;f+=.05){let sum=0,n=0;for(const x of vals){if(delta<0&&x.d<=-delta+2)continue;const alt=refBase(ref0+dir*(x.d+delta),dir),v=loss(x.v,x.wt,alt,f);if(v!==null){sum+=v;n++}}if(n<15)continue;const avg=sum/n, gain=nullLoss-avg;if(!best||gain>best.gain)best={delta,f,avg,gain,n}}}
if(!best||best.gain<.055||best.avg>.19||best.gain<nullLoss*.23)return null;
// Indel direction depends on strand and on which allele follows the reference; do not label ins/del without sequence reconstruction.
const before=Array.from({length:12},(_,i)=>refBase(ref0+dir*(i-12),dir)).join('');const wt=Array.from({length:32},(_,i)=>refBase(ref0+dir*i,dir)).join('');const alt=Array.from({length:32},(_,i)=>refBase(ref0+dir*(i+best.delta),dir)).join('');
return {read,k,ref0,dir,pre,nullLoss,...best,wt:before+wt,alt:before+alt,anchorQuality:anchor.ok};}
function findCandidates(read){const all=[];for(let k=32;k<read.bases.length-40;k+=2){const anchor=estimateAnchor(read,k);if(!anchor)continue;const c=scan(read,k,anchor);if(c)all.push(c)}all.sort((a,b)=>b.gain-a.gain);const selected=[];for(const c of all){if(selected.every(x=>Math.abs(x.k-c.k)>18))selected.push(c);if(selected.length===12)break}return selected;}
function show(c){el('readselect').value=state.reads.indexOf(c.read);viewTo(c.k-25,65);el('v6detail').textContent=`Lecture : ${c.read.name}\nTransition ABI : base ${c.k+1} (approximation)\nAncre référence : ${c.ref0+1} (approximation)\nDécalage en sens d'acquisition : ${c.delta>0?'+':''}${c.delta} bases\nGain de modèle (non calibré) : ${c.gain.toFixed(3)}\n\nSéquence guidée par référence : ${c.wt}\nSéquence décalée hypothétique : ${c.alt}\n\nATTENTION : les nucléotides de l'allèle alternatif ne sont PAS reconstruits de novo. Une insertion ne peut pas être séquencée par ce modèle. Le type, les coordonnées et le variant ne sont pas confirmés.`}
function render(){const body=el('v6rows');body.replaceChildren();for(const c of candidates){const tr=document.createElement('tr');for(const val of [c.read.name,c.k+1,c.ref0+1,(c.delta>0?'+':'')+c.delta,c.gain.toFixed(3),c.f.toFixed(2)]){const td=document.createElement('td');td.textContent=val;tr.append(td)}tr.onclick=()=>show(c);body.append(tr)}}
function run(){const status=el('v6status');candidates.length=0;el('v6rows').replaceChildren();el('v6detail').textContent='';if(!state.ref||!state.reads.length||state.reads.some(r=>!r.alignment)){status.textContent='Chargez une référence NM_, puis cliquez sur « Lire et analyser localement ».';return}status.textContent='Analyse indépendante des lectures en cours…';setTimeout(()=>{try{for(const read of state.reads)candidates.push(...findCandidates(read));candidates.sort((a,b)=>b.gain-a.gain);render();status.textContent=candidates.length?`${candidates.length} régions exploratoires : chaque lecture est analysée indépendamment contre le NM_. Aucun variant n'est confirmé.`:'Aucun signal n’a satisfait les critères exploratoires. Cela n’exclut PAS un variant.';}catch(e){status.textContent='Erreur : '+e.message;console.error(e)}},30)}
el('v6scan').addEventListener('click',run);
el('v6export').addEventListener('click',()=>{const rows=[['lecture','base_ABI_approximative','position_NM_approximative','decalage_acquisition','gain_non_calibre','fraction_modele'],...candidates.map(c=>[c.read.name,c.k+1,c.ref0+1,c.delta,c.gain,c.f])];const csv=rows.map(row=>row.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='SVIB_V6_regions_exploratoires.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
})();
